# Generated by Django 3.2 on 2021-04-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fotoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img', models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='static/images/')),
                ('author', models.CharField(max_length=120)),
                ('url_from', models.URLField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
