# Generated by Django 3.2 on 2021-04-29 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotonews',
            name='timepostdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fotonews',
            name='url_from',
            field=models.URLField(default='http://fotodnya.site', max_length=300),
        ),
    ]
