# Generated by Django 3.2 on 2021-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0002_auto_20210429_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonews',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='fotonews',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotonews',
            name='timepostdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotonews',
            name='url_from',
            field=models.URLField(blank=True, default='http://fotodnya.site', max_length=300, null=True),
        ),
    ]
