# Generated by Django 3.2 on 2021-04-29 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0003_auto_20210429_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonews',
            name='author',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
