# Generated by Django 3.2 on 2021-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0004_alter_fotonews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonews',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
