# Generated by Django 3.2 on 2021-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0005_alter_fotonews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonews',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
    ]
