# Generated by Django 3.2 on 2021-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodnya', '0006_alter_fotonews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonews',
            name='url_from',
            field=models.URLField(blank=True, default='http://fotodnya.site', max_length=300),
        ),
    ]
